M48
; DRILL file {KiCad (6.0.7)} date Mon Mar 20 21:14:04 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-20T21:14:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
%
G90
G05
T1
X20.376Y-174.442
X20.574Y-25.4
X268.306Y-25.826
X268.306Y-174.58
T0
M30
