M48
; DRILL file {KiCad (6.0.7)} date Sat Nov 19 14:58:57 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-19T14:58:57-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
%
G90
G05
T1
X21.508Y-174.072
X21.59Y-46.99
X347.878Y-174.015
X347.898Y-47.015
T0
M30
